# This is a workflow to execute Task

name: API Test (Python+request)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "API_Test"
  API_Test:
    # The test will execute on windows machine
    runs-on: windows-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository "pwcdemo
      - name: Install Project
        uses: actions/checkout@v3
        
      # Install Python    
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # Install dependencies
      - name: Install dependencies
        run: |
          pwd
          python -m pip install --upgrade pip
          pip install --default-timeout=100 -r /API_Test/requirement.txt
          
      # Execute api test
      - name: Run pytest
        run: pytest -v --html=./API_Test/test_reports/report.html

      # Upload test report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: API-test-report
          path: API_Test/test_reports
          retention-days: 5
