# This is a workflow to execute Task

name: API Test (Python+request)

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "UI_Test"
  API_Test:
    # The test will execute on windows machine
    runs-on: windows-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository "pwcdemo
      - name: Install Project
        uses: actions/checkout@v3 
        
      # Install Node with version
      - name: Install node dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # Install Playwright dependencies    
      - name: Install playwright dependencies
        run: |
         npm ci
         npx playwright install chromium
         
      # Execute playwright test
      - name: Run playwright test
        run: npx playwright test

      # Upload test report
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 5
