# This is a basic workflow to help you get started with Actions

name: Playwright Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Install Project
        uses: actions/checkout@v3 

      - name: Install node dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install playwright dependencies
        run: |
         npm ci
         npx playwright install
      
      - name: Run playwright test
        run: npx playwright test --reporter=list -g "Add Emplyoee and Verify"
        
      - name: check current path
        run: |
          echo "$PWD"
          echo "dir"
          echo "$dir"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
